# Generated by Django 3.1 on 2020-08-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200831_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='faculty_offers_course',
            name='course',
        ),
        migrations.RemoveField(
            model_name='faculty_offers_course',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='course_rev',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='student_rev',
        ),
        migrations.RemoveField(
            model_name='student_registers_course',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student_registers_course',
            name='student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Faculty_offers_course',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Student_registers_course',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
